// Playwright @playwright/test config for the amanuensis web app E2E suite (M8.9).
//
// Per project policy (CLAUDE.md): @playwright/test (Node/TypeScript) — never the
// Python `playwright` client. The FastAPI server is booted via `webServer` so
// `playwright test` is the single entrypoint for both spinning the app up and
// driving it.
//
// AMANUENSIS_WORKSPACE is plumbed into the spawned uvicorn process so the
// server resolves the planted fixture workspace at request time. The fixture
// is generated by `globalSetup.ts` before any test runs.

import { defineConfig } from "@playwright/test";
import * as path from "node:path";

const FIXTURE_WORKSPACE = path.resolve(__dirname, "fixtures", "workspace");
const STRESS_WORKSPACE = path.resolve(__dirname, "fixtures", "stress-workspace");
const PORT = 8723;
const BASE_URL = `http://127.0.0.1:${PORT}`;

// Which workspace the booted server points at is selected by an env var
// that the globalSetup script writes / reads. Tests that need the stress
// workspace switch via `test.use({ baseURL: ... })` is NOT enough — the
// server reads the env once at boot. M8.9 keeps it simple: the same uvicorn
// process serves all three specs from a single workspace whose fixture
// already contains:
//   - source `phase1-smoke`: 1 atom, 1 relation (smoke + state-persistence)
//   - source `phase1-stress`: ~250 atoms, ~750 relations (stress)
// 250/750 is the documented downgrade from the 1000/3000 target — see
// README.md for the rationale.

export default defineConfig({
  testDir: ".",
  testMatch: /.*\.spec\.ts$/,
  fullyParallel: true,
  workers: 4,
  retries: process.env.CI ? 1 : 0,
  reporter: [
    ["html", { outputFolder: "playwright-report", open: "never" }],
    ["list"],
  ],
  globalSetup: require.resolve("./globalSetup.ts"),
  use: {
    baseURL: BASE_URL,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  webServer: {
    // Boot uvicorn from the project root so `amanuensis.web.app:app` resolves
    // via the editable install. `uv run --no-sync` per project policy.
    //
    // Two macOS workarounds prepend the actual command:
    //   1. globalSetup runs AFTER webServer starts; the fixture workspace
    //      may not exist yet. We build it inline here too. The Python
    //      builder is idempotent; the second invocation from globalSetup
    //      becomes a no-op when the .built sentinel is present.
    //   2. `chflags nohidden` on `.venv/**/*.pth` — see globalSetup.ts
    //      for the rationale. Must happen BEFORE uvicorn launches, hence
    //      inlined here.
    command: [
      "cd ../..",
      // macOS .pth hidden-flag self-heal (see globalSetup.ts rationale).
      "find .venv -name '*.pth' -exec chflags nohidden {} + 2>/dev/null || true",
      // Plant the fixture workspace BEFORE uvicorn binds the port.
      // Direct venv-python invocation avoids `uv run` overhead and any
      // `uv sync` side-effects between calls.
      ".venv/bin/python tests/e2e/_fixture_builder.py tests/e2e/fixtures/workspace",
      // Launch uvicorn from the venv binary directly. PYTHONPATH is set
      // via `env:` below as a belt-and-braces measure: even if the
      // editable-install .pth gets re-hidden by some macOS quirk between
      // chflags and python launch, the explicit src path keeps the
      // import resolvable.
      ".venv/bin/uvicorn amanuensis.web.app:app --host 127.0.0.1 --port 8723",
    ].join(" && "),
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    env: {
      AMANUENSIS_WORKSPACE: FIXTURE_WORKSPACE,
      // Surface the stress workspace path too — currently unused by the
      // server but recorded for inspection in `playwright-report`.
      AMANUENSIS_STRESS_WORKSPACE: STRESS_WORKSPACE,
      // Belt-and-braces import resolution (see command comment).
      PYTHONPATH: path.resolve(__dirname, "..", "..", "src"),
    },
  },
});
